### ISSUE TITLE
在iPhone6 缩放模式下的问题

### ISSUE THREAD

**Issue by pilgrim1385** [nixzhu/Ruler#5]
iPhone6 设置-显示与亮度-显示模式-放大，这时UIScreen.main().bounds.size.width = 320，而nativeBounds不能区分这种情况，还会按iPhone6的尺寸显示。而实际上这种情况下应该按iPhone5的尺寸显示。

**Comment by nixzhu** [comment]
Thanks for test! I will investigate it. A pull request is welcome.
pilgrim1385 notifications@github.com于2016年10月14日 周五11:19写道：

**Comment by nixzhu** [comment]
Version 1.0.1 fixed this issue.
